---
title: "COVID19 in Germany"
description: |
  Exploring the impact of COVID19 in Germany
author:
  - name: Ibrahim Al-Hindi
date: 09-13-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r libraries}
library(tidyverse)
library(tidycovid19)
```


```{r data}
covid_data <- download_merged_data(cached = TRUE, silent = TRUE)

ger <- covid_data %>%
  filter(country == "Germany") %>% 
  select(country:recovered, icu_patients, total_vaccinations) %>% 
  mutate(across(icu_patients : total_vaccinations, ~ replace_na(.x, 0)),
         daily_confirmed = c(0, diff(confirmed)),
         daily_deaths = c(0, diff(deaths)),
         daily_recovered = c(0, diff(recovered)),
         daily_vaccinations = c(0, diff(total_vaccinations))) %>% 
  select(date, daily_confirmed, confirmed, daily_deaths, deaths, daily_recovered, recovered, icu_patients, daily_vaccinations, total_vaccinations) %>% 
  rename(acc_confirmed = confirmed,
         acc_deaths = deaths,
         acc_recovered = recovered,
         acc_vaccinations = total_vaccinations)



```



























